project_root2/src/photo/urls.py
# -*- coding: utf-8 -*-
from photo.views import about_project, authors_post_likes, comment_edit, lesson_detail, \
    lessons_list, post_detail,  post_edit, posts_list, posts_list_user, search_user_username, \
    simple_example, user_detail, user_main_page, users_list, logout \

from django.conf.urls import url



urlpatterns = [
    url(r'^about/$', about_project, name='about_project'),
    url(r'authors_post_likes/(?P<post_id>\d+)/$', authors_post_likes, name='authors_post_likes'),
    url(r'comment/edit/(?P<comment_id>\d+)/$', comment_edit, name='comment_edit'),
    url(r'form_search_user_username/$', search_user_username, name='search_user_username'),
    url(r'^lessons/list/$', lessons_list, name='lessons_list'),
    url(r'lesson/detail/(?P<lesson_id>\d+)/$', lesson_detail, name='lesson_detail'),
    url(r'post/edit/(?P<post_id>\d+)/$', post_edit, name='post_edit'),
    url(r'post/detail/(?P<post_id>\d+)/$', post_detail, name='post_detail'),
    url(r'^posts/list/$', posts_list, name='posts_list'),
    url(r'^posts/list/user/$', posts_list_user, name='posts_list_user'),
    url(r'^simple_example/$', simple_example, name='simple_example'),
    url(r'user_main_page/$', user_main_page, name='user_main_page'),
    url(r'^users/list/$', users_list, name='users_list'),
    url(r'user/detail/(?P<user_id>\d+)/$', user_detail, name='user_detail'),
    url(r'^logout/$', logout, name='logout'),
]

project_root2/src/project/urls.py
# -*- coding: utf-8 -*-

"""project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url('^', include('django.contrib.auth.urls')),
    url('', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

project_root2/src/photo/forms.py
from django import forms
from photo.models import Post, Comment



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'photo')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )


class SearchUserFormByUsername(forms.Form):
    query = forms.CharField(label='Enter a keyword to search for',
    widget=forms.TextInput(attrs={'size': 32, 'class':'form-control search-query'}))

project_root2/src/photo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from photo.models import Post, PhotoUser, Mark
from photo.models import Comment, Like, Tag, Lesson
from photo.forms import PostForm, CommentForm, SearchUserFormByUsername
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.db.models import Count
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import json
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect
from django.contrib import auth



# http://127.0.0.1:8000/photo/about/
@login_required
def about_project(request):
    return render(request, 'photo/about_project.html', {})


# http://127.0.0.1:8000/photo/posts/list/
@login_required
def posts_list(request):
    posts = Post.objects.all().select_related().annotate(num_likes=Count('likes')).order_by('-date_created') [:20]
    posts = posts.annotate(num_comments=Count('comments'))
    return render(request, 'photo/posts_list.html', {'posts': posts})


# http://127.0.0.1:8000/posts/list/user/
@login_required
def posts_list_user(request):
    posts = Post.objects.filter(user_id=request.user.id).annotate(num_likes=Count('likes')).order_by('-date_created')
    posts = posts.annotate(num_comments=Count('comments'))

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('http://127.0.0.1:8000/photo/posts/list/user/')
    else:
        form = PostForm()

    return render(request, 'photo/posts_list_user.html', {'posts': posts, 'form': form})


# http://127.0.0.1:8000/post/detail/65
def post_detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)

    marks = Mark.objects.filter(post=post)

    marks_rounded = {}
    mark_composition = marks.aggregate(avg_comp = Avg('mark_composition'))
    if mark_composition['avg_comp'] != None:
        marks_rounded['Композиция'] = round(mark_composition['avg_comp'], 2)
    else:
        marks_rounded['Композиция'] = 'нет оценок'

    mark_settings = marks.aggregate(avg_set = Avg('mark_settings'))
    if mark_settings['avg_set'] != None:
        marks_rounded['Настройки/техника исполнения'] = round(mark_settings['avg_set'], 2)
    else:
        marks_rounded['Настройки/техника исполнения'] = 'нет оценок'

    mark_lighting = marks.aggregate(avg_light = Avg('mark_lighting'))
    if mark_lighting['avg_light'] != None:
        marks_rounded['Освещение'] = round(mark_lighting['avg_light'], 2)
    else:
        marks_rounded['Освещение'] = 'нет оценок'

    mark_color = marks.aggregate(avg_color = Avg('mark_color'))
    if mark_color['avg_color'] != None:
        marks_rounded['Цвет'] = round(mark_color['avg_color'], 2)
    else:
        marks_rounded['Цвет'] = 'нет оценок'

    mark_idea = marks.aggregate(avg_idea = Avg('mark_idea'))
    if mark_idea['avg_idea'] != None:
        marks_rounded['Идея'] = round(mark_idea['avg_idea'], 2)
    else:
        marks_rounded['Идея'] = 'нет оценок'

    likes = Like.objects.select_related('user').filter(object_id=post_id)

    comments = Comment.objects.select_related('user').filter(object_id=post_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.object_id = post_id
            comment.content_type_id = 12
            comment.save()
            return redirect('http://127.0.0.1:8000/photo/post/detail/%d/' % post.id)
    else:
        form = CommentForm()

    return render(request, 'photo/post_detail.html',
                  {'post': post, 'comments': comments, 'likes': likes,
                   'marks_rounded': marks_rounded, 'form': form})


def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post = get_object_or_404(Post, comments=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.object_id = post.id
            comment.content_type_id = 12
            comment.save()
            return redirect('http://127.0.0.1:8000/photo/post/detail/%d/' % post.id)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'photo/comment_edit.html', {'comment': comment, 'form': form})


# http://127.0.0.1:8000/photo/authors_post_likes/2/
def authors_post_likes (request, post_id):
    likes = Like.objects.select_related().filter(object_id=post_id)
    return render(request, 'photo/authors_post_likes.html', {'likes': likes})


# http://127.0.0.1:8000/photo/users/list/
@login_required
def users_list(request):
    users = PhotoUser.objects.filter(user_status=0).defer('password',
                                        'last_login', 'is_superuser', 'first_name', 'last_name', 'email',
                                        'is_active', 'is_staff', 'date_joined', 'avatar')[:20]
    return render(request, 'photo/users_list.html', {'users': users})


# http://127.0.0.1:8000/photo/user/detail/2/
@login_required
def user_detail(request, user_id):
    user = get_object_or_404(PhotoUser, pk=user_id)
    posts = Post.objects.filter(user=user).annotate(num_likes=Count('likes')).order_by('-date_created')  #[:20]
    return render(request, 'photo/user_detail.html', {'user': user, 'posts': posts})


# http://127.0.0.1:8000/photo/user?username=Антон
@login_required
def users_by_name(request):
    username=request.GET['username']
    usernames = PhotoUser.objects.filter(user_status=0, username__icontains=username).defer('password',
                                        'last_login', 'is_superuser', 'first_name', 'last_name', 'email',
                                        'is_active', 'is_staff', 'date_joined', 'about_user', 'avatar')
    return render(request, 'photo/users_by_name.html', {'usernames': usernames})


# http://127.0.0.1:8000/photo/lessons/list/
@login_required
def lessons_list(request):
    lessons_list = Lesson.objects.all()
    paginator = Paginator(lessons_list, 20)
    page = request.GET.get('page')
    try:
        lessons = paginator.page(page)
    except PageNotAnInteger:
        lessons = paginator.page(1)
    except EmptyPage:
        lessons = paginator.page(paginator.num_pages)

    return render(request, 'photo/lessons_list.html', {'lessons': lessons})


# http://127.0.0.1:8000/photo/lesson/detail/2/
@login_required
def lesson_detail(request, lesson_id):
    lesson = get_object_or_404(Lesson, pk=lesson_id)
    return render(request, 'photo/lesson_detail.html', {'lesson': lesson})


# http://127.0.0.1:8000/photo/post?tag_name=Landscape
@login_required
def posts_by_tag(request):
    tag_name = request.GET['tag_name']
    posts = Post.objects.select_related().defer('user__last_login','user__password',
     'user__last_login', 'user__is_superuser', 'user__about_user', 'user__user_status',
     'user__first_name', 'user__last_name', 'user__email', 'user__is_active', 'user__is_staff',
     'user__date_joined', 'user__avatar').filter(tags__tag_name=tag_name)
    return render(request, 'photo/posts_by_tag.html', {'tag_name': tag_name, 'posts': posts})


# http://127.0.0.1:8000/photo/lesson?tag_name=Landscape
@login_required
def lessons_by_tag(request):
    tag_name=request.GET['tag_name']
    lessons = Lesson.objects.filter(tags__tag_name=tag_name)
    return render(request, 'photo/lessons_by_tag.html', {'tag_name': tag_name, 'lessons': lessons})


# @login_required
def simple_example(request):
    if request.method == "GET":
        return render(request, 'photo/simple_example.html')
    if request.method == "POST":
        data = '1'
        context = {"data": data}
        return HttpResponse(json.dumps(context), content_type="application/json")


# http://127.0.0.1:8000/photo/posts/list/user/
@login_required
def posts_list_user(request):
    posts = Post.objects.filter(user_id=request.user.id).annotate(num_likes=Count('likes')).order_by('-date_created')
    posts = posts.annotate(num_comments=Count('comments'))

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('http://127.0.0.1:8000/photo/posts/list/user/')
    else:
        form = PostForm()

    return render(request, 'photo/posts_list_user.html', {'posts': posts, 'form': form})


def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES or None, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('http://127.0.0.1:8000/photo/posts/list/user/')
    else:
        form = PostForm(instance=post)
    return render(request, 'photo/post_edit.html', {'post': post, 'form': form})


def search_user_username(request):
    if request.method == "GET":
        form = SearchUserFormByUsername()
        params = dict()
        params["search"] = form
        return render(request, 'photo/form_search_user_username.html', params)

    if request.method == "POST":
        form = SearchUserFormByUsername(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            users = PhotoUser.objects.filter(username__icontains=query)
            context = {"query": query, "users": users}

project_root2/src/templates/photo/about_project.html
{% extends "base.html" %}

{% block title %} О проекте {% endblock %}


{% block content %}

    <div class = "item-about-opportunity1">
        <p class="font-weight-bold"> Делись фотографиями </p>
        <img class = "item-about-picture"
             src = "/static/img/1_about.jpg" alt = "Делись фотографиями">
    </div>

    <div class = "item-about-opportunity2">
        <p class="font-weight-bold"> Оценивай работы других фотографов </p>
        <img class = "item-about-picture"
            src = "/static/img/2_about.jpg" alt = "Оценивай работы">
    </div>

    <div class = "item-about-opportunity3">
      <p class="font-weight-bold"> Давай советы и критикуй </p>
        <img class = "item-about-picture"
             src = "/static/img/3_about.jpg" alt = "Давай советы">
    </div>

    <div class = "item-about-opportunity4">
      <p class="font-weight-bold">  Читай уроки фотографии </p>
        <img class = "item-about-picture" class="img-fluid"
             src = "/static/img/4_about.jpg" alt = "Читай уроки">
    </div>

{% endblock %}

project_root2/src/templates/photo/authors_post_likes.html
{% extends "base.html" %}

{% block title %} Лайки {% endblock %}


{% block content %}

        <div class="count-likes">
            <p><span class="font-weight-bold"> Количество лайков:</span> {{likes| length}} </p>
        </div>

        <div class = "authors-likes">
            <p class="font-weight-bold"> Авторы лайков:</p>
            {% for like in likes %}
                <p><a href="photo/user/detail/{{ like.user.id }}/"> {{ like.user.username}} </a></p>
            {% endfor %}
        </div>

{% endblock %}

project_root2/src/templates/photo/comment_edit.html
{% extends "base.html" %}

{% block title %} Комментарий {% endblock %}


{% block content %}

    <form method="POST" action="{% url 'photo:comment_edit' comment_id=comment.id %}" class="comment-form">
        {% csrf_token %}
        <textarea name="text" class="form-control" id="exampleTextarea" rows="3"> {{comment.text}} </textarea>

        <div class="button-under-textarea">
            <input type="submit" class="btn btn-outline-warning btn-sm"  value="Сохранить"/>
        </div>
    </form>

{% endblock %}

project_root2/src/templates/photo/form_search_post_tag.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Поиск {% endblock %}


{% block content %}

    <form method="POST" action="" class="search-bytag-post-form">
        {% csrf_token %}
        <div class="input-group input-group-sm">
            {{ form_search_post_tag.tag_name.errors }}
            {{ form_search_post_tag.tag_name }}
            <button class = "btn btn-search" type="submit"> Поиск </button>
        </div>
    </form>

{% endblock %}


{% block javascript %}

<script src="/static/search-post-tag.js"> </script>

{% endblock %}

project_root2/src/templates/photo/form_search_user_username.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Поиск {% endblock %}


{% block content %}

    <div class="search-user">
        <form method="POST" action="" class="search-byusername-user-form">
            {% csrf_token %}
            <div class="input-group input-group-sm">
                {{ search.query.errors }}
                {{ search.query }}
                <button class = "btn btn-search" type="submit">Поиск</button>
            </div>
        </form>
        <div class="users"></div>
    </div>

{% endblock %}


{% block javascript %}

<script src="/static/search-user-username.js"> </script>

{% endblock %}

project_root2/src/templates/photo/lesson_detail.html
{% extends "base.html" %}

{% block title %} Урок инфо {% endblock %}


{% block content %}

    <div class="lesson-detail">
        <p><span class="font-weight-bold">Дата создания:</span> {{ lesson.date_created }} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <span class="font-weight-bold"> Заголовок: </span> {{ lesson.title }} </p>
        <p> {{ lesson.text }} </p>
    </div>

{% endblock %}

project_root2/src/templates/photo/lessons_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Уроки {% endblock %}


{% block content %}
    <div class="found-count-in-lessons-list">
        <h3> <span class="badge badge-primary"> Найдено уроков: {{ lessons| length }} </span> </h3>
    </div>

    <div class = "lessons-list">
        {% for lesson in lessons %}
            <div class="alert alert-warning" role="alert">
                <p class="font-weight-bold">
                   {{ lesson.date_created }} <a href="photo/lesson/detail/{{ lesson.id }}/">
                    {{ lesson.title }} </a>
                </p>
                <p> {{lesson.text|truncatewords:7 }} </p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

project_root2/src/templates/photo/post_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Пост инфо {% endblock %}


{% block content %}

    <div class = "post-detail-content">

        <p><span class="font-weight-bold"> Дата публикации: </span> {{post.date_created}}  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <span class="font-weight-bold"> Пользователь: </span><a href="photo/user/detail/{{ post.user.id }}/">
                {{post.user.username}} </a></p>
        <p>  {{ post.text|linebreaksbr }} </p>
        <p> {% if post.photo %}
                <img src = "{{ post.photo.url }}" class="img-fluid">
            {% endif %} </p>

        <div class="button-edit-post">
            {% if post.user_id == request.user.id %}
                <a href="{% url 'photo:post_edit' post_id=post.id %}">
                    <input type="submit" class="btn btn-outline-warning btn-sm" value="Редактировать пост"/>
                </a>
            {% endif %}
        </div>

        <span class="font-weight-bold" class="avg-mark"> Средние оценки: </span></br>
        {% for key, value in marks_rounded.items %}
            <span class="badge badge-pill badge-info">
            {{ key }}: {{ value }} </span> &nbsp; &nbsp; &nbsp;
        {% endfor %}

        <!--количество лайков и их авторы-->
        <div class="like-count"> <span class="font-weight-bold">
            Лайки: </span> {{likes| length}} </div>
        <a href="photo/authors_post_likes/{{ post.id }}/"> Авторы лайков здесь </a>


        <!--комментарии к посту-->
        <p> <span class="font-weight-bold"> Комментарии: </span> {{comments| length}} </p>
        <div class="new_comment">   </div>

        {% for comment in comments %}
            <div id="comment-content">
                <p> {{comment.date_created}} &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <a href="photo/user/detail/{{ comment.user.id }}/"> {{comment.user.username}} </a></p>
                <p> {{comment.text}}  </p>

                <div class="button-edit-post">
                    {% if comment.user_id == request.user.id %}
                        <a href="{% url 'photo:comment_edit' comment_id=comment.id %}">
                            <input type="submit" class="btn btn-outline-warning btn-sm"
                            value="Редактировать комментарий"/>
                        </a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

        <!--форма создания-->
        <form method="POST">
            {% csrf_token %}
            <textarea name="text" class="form-control" id="exampleTextarea" rows="3">  </textarea>

            <input type="submit" class="btn btn-outline-warning btn-sm"  value="Добавить комментарий"/>
        </form>

    </div>

{% endblock %}

project_root2/src/templates/photo/post_edit.html
{% extends "base.html" %}

{% block title %} Пост {% endblock %}


{% block content %}

    <form method="POST" action="{% url 'photo:post_edit' post_id=post.id %}" class="post-form">
        {% csrf_token %}
        <textarea name="text" class="form-control" id="exampleTextarea" rows="3"> {{post.text}} </textarea>

        <div class="button-under-textarea">
            <input type="submit" class="btn btn-outline-warning btn-sm"  value="Сохранить"/>
        </div>
    </form>

{% endblock %}

project_root2/src/templates/photo/posts_list.html
{% extends "base.html" %}

{% block title %} Список постов {% endblock %}

{% block content %}

        <div class="found-something">
            <h3><span class="badge badge-primary"> Найдено постов: {{ posts| length }} </span></h3>
        </div>

        <div class = "users-list-content">
            {% for post in posts %}
                 <div class="alert alert-warning" role="alert">
                    <p> <span class="font-weight-bold"> Дата публикации: </span> {{post.date_created}}
                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        <span class="font-weight-bold"> Пользователь: </span>
                        <a href="photo/user/detail/{{ user.id }}/"> {{post.user.username}} </a>
                    </p>
                    <p><a href="photo/post/detail/{{ post.id }}/"> {{ post.text|linebreaksbr }} </a></p>
                    <p class="badge badge-pill badge-info"> Лайки: {{post.num_likes}} </p>
                    <p class="badge badge-pill badge-info"> Комментарии: {{post.num_comments}} </p><br>
                 </div>
            {% endfor %}
        </div>

{% endblock %}

project_root2/src/templates/photo/posts_list_user.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Список постов {% endblock %}


{% block content %}

    <!--форма создания-->
    <form method="POST">
        {% csrf_token %}
        <textarea name="text" class="form-control" id="exampleTextarea" rows="3">  </textarea>
        <input type="submit" class="btn btn-outline-warning btn-sm" value="Добавить пост"/>
    </form>

    <!--список постов-->
    <div class="found-something">
        <h3><span class="badge badge-primary"> Найдено постов: {{ posts| length }} </span></h3>
    </div>

    <div class="posts-list">
        {% for post in posts %}
            <span class="font-weight-bold"> Дата публикации: </span> {{post.date_created}} <br>
            <p><a href="photo/post/detail/{{ post.id }}/"> {{ post.text|linebreaksbr }} </a></p>
            <p> {% if post.photo %}
                    <img src = "{{ post.photo.url }}" class="img-fluid">
                {% endif %} </p>

            <div class="button-edit-post">
                {% if post.user_id == request.user.id %}
                    <a href="{% url 'photo:post_edit' post_id=post.id %}">
                        <input type="submit" class="btn btn-outline-warning btn-sm" value="Редактировать пост"/>
                    </a>
                {% endif %}
            </div>

            <p class="badge badge-pill badge-info"> Лайки: {{post.num_likes}} </p>
            <p class="badge badge-pill badge-info"> Комментарии: {{post.num_comments}} </p><br>
        {% endfor %}
    </div>

{% endblock %}

project_root2/src/templates/photo/user_detail.html
{% extends "base.html" %}

{% block title %} Пользователь инфо {% endblock %}


{% block content %}

        <div class = "user-detail-about-user">
            <p><span class="font-weight-bold"> Имя: </span> {{user.username}} </p>
            <p><span class="font-weight-bold"> О себе: </span> {{ user.about_user }} </p>
        </div>

        <div class = "user-detail-avatar-position">
            <p> {% if user.avatar %}
                    <img class = "user-detail-avatar" src = "{{ user.avatar.url }}">
                {% endif %} </p>
        </div>

        <div class = user-detail-comment-position>
            <p class="badge badge-pill badge-warning"> Количество постов: {{ posts| length }} </p>
            {% for post in posts %}
                <p> {{ post.date_created }} </p>
                <p><a href="photo/post/detail/{{ post.id }}/"> {{ post.text }} </a></p>

                <p class="badge badge-pill badge-info"> Лайки: {{post.num_likes}} </p>
            {% endfor %}
        </div>

{% endblock %}

project_root2/src/templates/photo/user_main_page.html
{% extends "base.html" %}

{% block title %} Пользователь инфо {% endblock %}


{% block content %}

    <div> {% if user.avatar %}
            <img src = "{{ user.avatar.url }}" class="img-fluid">
        {% endif %}
    </div>

    <div>
        <p><span class="font-weight-bold"> Имя: </span> {{user.username}} </p>
        <p><span class="font-weight-bold"> О себе: </span> {{user.about_user}} </p>
    </div>

{% endblock %}

project_root2/src/templates/photo/users_list.html
{% extends "base.html" %}

{% block title %} Список пользователей {% endblock %}


{% block content %}

    <div class="found-something">
        <h3><span class="badge badge-primary"> Найдено пользователей: {{ users| length }} </span></h3>
    </div>

    <div class = "users-list-content">
        {% for user in users %}
            <div class="alert alert-warning" role="alert">
                <span class="item-user"> <a href="photo/user/detail/{{ user.id }}/">
                    {{ user.username }} </a> </span> <span> {{user.about_user|truncatewords:7}} </span>
            </div>
        {% endfor %}
    </div>

{% endblock %}