project_root2/src/photo/urls.py
# -*- coding: utf-8 -*-
from photo.views import about_project, authors_post_likes, comment_edit, lesson_detail, \
    lessons_list, post_detail,  post_edit, posts_list, posts_list_user, search_user_username, \
    simple_example, user_detail, user_main_page, users_list, logout \

from django.conf.urls import url



urlpatterns = [
    url(r'^about/$', about_project, name='about_project'),
    url(r'authors_post_likes/(?P<post_id>\d+)/$', authors_post_likes, name='authors_post_likes'),
    url(r'comment/edit/(?P<comment_id>\d+)/$', comment_edit, name='comment_edit'),
    url(r'form_search_user_username/$', search_user_username, name='search_user_username'),
    url(r'^lessons/list/$', lessons_list, name='lessons_list'),
    url(r'lesson/detail/(?P<lesson_id>\d+)/$', lesson_detail, name='lesson_detail'),
    url(r'post/edit/(?P<post_id>\d+)/$', post_edit, name='post_edit'),
    url(r'post/detail/(?P<post_id>\d+)/$', post_detail, name='post_detail'),
    url(r'^posts/list/$', posts_list, name='posts_list'),
    url(r'^posts/list/user/$', posts_list_user, name='posts_list_user'),
    url(r'^simple_example/$', simple_example, name='simple_example'),
    url(r'user_main_page/$', user_main_page, name='user_main_page'),
    url(r'^users/list/$', users_list, name='users_list'),
    url(r'user/detail/(?P<user_id>\d+)/$', user_detail, name='user_detail'),
    url(r'^logout/$', logout, name='logout'),
]

project_root2/src/project/urls.py
# -*- coding: utf-8 -*-

"""project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url('^', include('django.contrib.auth.urls')),
    url('', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

project_root2/src/templates/base.html
{% load staticfiles %}

<html>
    <head>

        <title>
            {% block title %} Фото Мир {% endblock %}
        </title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="/static/script-menu.js"></script>

        <link rel="stylesheet" href="/static/photo.css">

    </head>


    <body>
    <div class="container">

        <div class="header">
            <div class="main-inscription">
                <h1><a href="{% url 'photo:about_project' %}"> Фото Мир - сеть для фотографов </a></h1>
            </div>

            <div>
                <a href="{% url 'photo:logout' %}">
                    <input type="submit" class="btn btn-outline-warning btn-sm"  value="Выход"/>
                </a>
            </div>

            <div class = "d-xl-none d-xs-block d-md-block d-lg-block">
                <img class="custom-img-fluid" src = "/static/img/main_picture_middle2.jpg"
                 alt = "Главное фото">
            </div>

            <div class = "d-none d-xl-block"
                 class="main-picture-big-below-inscription">
                <img class="custom-img-fluid" src = "/static/img/main_picture_big4.jpg"
                     alt = "Главное фото" width="1112" height="63">
            </div>
        </div>


        <div class="item-nav">
            <nav class="navbar navbar-toggleable-md navbar-light">
              <button class="navbar-toggler" type="button" data-toggle="collapse"
                      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                      aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'photo:user_main_page' %}"> Мой профиль </a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'photo:posts_list_user' %}"> Мои посты </a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'photo:posts_list' %}"> Новые посты </a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'photo:users_list' %}"> Все пользователи </a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'photo:lessons_list' %}"> Уроки фотографии </a>
                 </li>
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Поиск </a>
                     <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'photo:search_user_username' %}">
                          Поиск пользователей</a>
                      <a class="dropdown-item" href="#">Поиск постов по тегам</a>
                      <a class="dropdown-item" href="#">Поиск уроков по тегам</a>
                     </div>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'photo:about_project' %}"> О проекте </a>
                 </li>
                </ul>
              </div>
            </nav>

        </div>

        {% block content %} {% endblock %}

        {% block javascript %} {% endblock %}

    </div>
    </body>

</html>